export type LeagueConfig = {
  slug: string;
  name: string;
  apiFootballLeagueId: number;
  altenarChampId?: number;
  eligibility?: "SENIOR_INTERNATIONAL_ONLY";
};

export const MVP_LEAGUES: LeagueConfig[] = [
  { slug: "world-cup", name: "World Cup", apiFootballLeagueId: 1, altenarChampId: 16807 },
  { slug: "champions-league", name: "Champions League", apiFootballLeagueId: 2, altenarChampId: 16808 },
  { slug: "europa-league", name: "Europa League", apiFootballLeagueId: 3, altenarChampId: 16809 },
  { slug: "friendlies", name: "Friendlies", apiFootballLeagueId: 10, eligibility: "SENIOR_INTERNATIONAL_ONLY" },
  { slug: "sul-americana", name: "Copa Sul-Americana", apiFootballLeagueId: 11 },
  { slug: "libertadores", name: "Libertadores", apiFootballLeagueId: 13, altenarChampId: 3709 },
  { slug: "premier-league", name: "Premier League", apiFootballLeagueId: 39, altenarChampId: 2936 },
  { slug: "championship", name: "Championship", apiFootballLeagueId: 40 },
  { slug: "fa-cup", name: "FA Cup", apiFootballLeagueId: 45 },
  { slug: "efl-cup", name: "EFL Cup", apiFootballLeagueId: 48 },
  { slug: "ligue-1", name: "Ligue 1", apiFootballLeagueId: 61, altenarChampId: 2943 },
  { slug: "ligue-2", name: "Ligue 2", apiFootballLeagueId: 62 },
  { slug: "coupe-de-france", name: "Coupe de France", apiFootballLeagueId: 66 },
  { slug: "brasileirao", name: "Brasileirao", apiFootballLeagueId: 71, altenarChampId: 11318 },
  { slug: "brasileirao-serie-b", name: "Brasileirao Serie B", apiFootballLeagueId: 72, altenarChampId: 11005 },
  { slug: "copa-do-brasil", name: "Copa do Brasil", apiFootballLeagueId: 73 },
  { slug: "bundesliga", name: "Bundesliga", apiFootballLeagueId: 78, altenarChampId: 2950 },
  { slug: "2-bundesliga", name: "2. Bundesliga", apiFootballLeagueId: 79 },
  { slug: "dfb-pokal", name: "DFB Pokal", apiFootballLeagueId: 81 },
  { slug: "eredivisie", name: "Eredivisie", apiFootballLeagueId: 88 },
  { slug: "knvb-beker", name: "KNVB Beker", apiFootballLeagueId: 90 },
  { slug: "primeira-liga", name: "Primeira Liga", apiFootballLeagueId: 94 },
  { slug: "taca-de-portugal", name: "Taca de Portugal", apiFootballLeagueId: 96 },
  { slug: "taca-da-liga", name: "Taca da Liga", apiFootballLeagueId: 97 },
  { slug: "denmark-superliga", name: "Danish Superliga", apiFootballLeagueId: 119 },
  { slug: "dbu-pokalen", name: "DBU Pokalen", apiFootballLeagueId: 121 },
  { slug: "argentina-primera-division", name: "Argentina Primera Division", apiFootballLeagueId: 128 },
  { slug: "serie-a", name: "Serie A", apiFootballLeagueId: 135, altenarChampId: 2942 },
  { slug: "serie-b", name: "Serie B", apiFootballLeagueId: 136 },
  { slug: "coppa-italia", name: "Coppa Italia", apiFootballLeagueId: 137 },
  { slug: "la-liga", name: "La Liga", apiFootballLeagueId: 140, altenarChampId: 2941 },
  { slug: "la-liga-2", name: "La Liga 2", apiFootballLeagueId: 141 },
  { slug: "copa-del-rey", name: "Copa del Rey", apiFootballLeagueId: 143 },
  { slug: "belgian-pro-league", name: "Belgian Pro League", apiFootballLeagueId: 144 },
  { slug: "belgian-cup", name: "Belgian Cup", apiFootballLeagueId: 147 },
  { slug: "scottish-premiership", name: "Scottish Premiership", apiFootballLeagueId: 179 },
  { slug: "scottish-fa-cup", name: "Scottish FA Cup", apiFootballLeagueId: 181 },
  { slug: "scottish-challenge-cup", name: "Scottish Challenge Cup", apiFootballLeagueId: 182 },
  { slug: "scottish-league-cup", name: "Scottish League Cup", apiFootballLeagueId: 185 },
  { slug: "super-lig", name: "Super Lig", apiFootballLeagueId: 203 },
  { slug: "turkiye-kupasi", name: "Turkiye Kupasi", apiFootballLeagueId: 206 },
  { slug: "mls", name: "MLS", apiFootballLeagueId: 253 },
  { slug: "belgian-super-cup", name: "Belgian Super Cup", apiFootballLeagueId: 519 },
  { slug: "france-trophee-des-champions", name: "Trophee des Champions", apiFootballLeagueId: 526 },
  { slug: "germany-super-cup", name: "German Super Cup", apiFootballLeagueId: 529 },
  { slug: "italy-super-cup", name: "Italian Super Cup", apiFootballLeagueId: 547 },
  { slug: "portugal-super-cup", name: "Portugal Super Cup", apiFootballLeagueId: 550 },
  { slug: "turkish-super-cup", name: "Turkish Super Cup", apiFootballLeagueId: 551 },
  { slug: "supercopa-espana", name: "Supercopa de Espana", apiFootballLeagueId: 556 },
  { slug: "supercopa-do-brasil", name: "Supercopa do Brasil", apiFootballLeagueId: 632 },
  { slug: "conference-league", name: "Conference League", apiFootballLeagueId: 848, altenarChampId: 31608 },
];
